version: "2"
services:
  app:
    container_name: flask
    build: .
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
  db:
    container_name: flask_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro